name: OneClickInstall scripts testing

on:
  push: 
    paths-ignore:
            #- '.github/**'
      - 'tests/**'
      - '**/README.md'

  schedule:
    - cron: '00 21 * * 6'  # At 21:00 on Saturday.
    
env: 
  BOX_DISTRIBUTION: generic
  RUNNER_IMAGE: ubuntu-22-04-x64
  RUNNER_REGION: fra1
  RUNNER_SIZE: s-4vcpu-8gb-intel

jobs:
  vagrant-up:
    name: "Run tests on ${{ matrix.boxes }}"
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        boxes: 
          - centos7
        # - centos8s
        #- centos9s
        #- debian9
        #- debian10
        #- debian11
        #- ubuntu1804
        #- ubuntu2004
        #- ubuntu2204

    steps:
    - name: Checkout code      
      uses: actions/checkout@v3
 
    - name: Set up Python 3.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Show Vagrant version
      run: vagrant --version

    - name: Install from production scripts
      if: ${{ github.event_name == 'push' }}
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        retry_on: error
        timeout_minutes: 180
        command: |
              cd tests/vagrant
              TEST_CASE='--production-install' \
              DISTR='generic' \
              OS='${{ matrix.boxes }}' \
              DOWNLOAD_SCRIPT='-ds true' \
              ARGUMENTS="-arg '--skiphardwarecheck true --makeswap false'" \
              vagrant up
        on_retry_command: |
              echo "RUN CLEAN UP: Destroy vagrant and one more try"
              cd tests/vagrant
              sleep 10
              vagrant destroy --force

    - name: Install from local scripts
      if: ${{ github.event_name == 'schedule' }}
      uses: nick-fields/retry@v2
      with:
        max_attempts: 2
        timeout_minutes: 180
        retry_on: error
        command: |
              cd tests/vagrant
              TEST_CASE='--local-install' \
              DISTR='generic' \
              OS='${{ matrix.boxes }}' \
              DOWNLOAD_SCRIPT='-ds false' \
              ARGUMENTS="-arg '--skiphardwarecheck true --makeswap false --localscripts true'" \
              vagrant up
        on_retry_command: |
              echo "RUN CLEAN UP: Destroy vagrant and one more try"
              cd tests/vagrant
              sleep 10
              vagrant destroy --force
